#%RAML 0.8
title: Message Broker API
baseUri: http://example.com
documentation:
  - title: Message Broker API
    content: Hey
/subscriptions:    
  description: Topic Subscription Management
  /evaluation/{topicName}/{clientId}:
    description: Temporary Subscription
    uriParameters:
      topicName:
        description: Name of the topic that client needs to subscribe to.
      clientId:
        description: An identifier of the client that is subscribing.
    put:
      description: Topic Subscription Interfaces
      queryParameters:
        wsCallbackEndpoint:
          description: A valid WS endpoint which will receive a POST request when a new message arrives for the subscribed topic. 
      responses:
        204:
  /durable/{topicName}/{clientId}:
      description: Durable Subscription
      uriParameters:
        topicName:
          description: Name of the topic that client needs to subscribe to.
        clientId:
          description: An identifier of the client that is subscribing.
      put:
        description: Durable Topic Subscription
        queryParameters:
          wsCallbackEndpoint:
            description: A valid WS endpoint which will receive a POST request when a new message arrives for the subscribed topic. 
        responses:
          204:
  /durable/{topicName}/{clientId}/unsubscribe:
      description: Unsubscribe from Durable Subscription
      uriParameters:
        topicName:
          description: Name of the topic that client needs to subscribe to.
        clientId:
          description: An identifier of the client that is subscribing.
      put:
        description: Durable Topic unsubscription
        responses:
          204:
/topics/evaluation/{topicName}/{clientId}:
  description: Publish to a Topic
  uriParameters:
    topicName:
      description: Name of the topic that client needs to subscribe to.
    clientId:
      description: An identifier of the client that is subscribing.
  post:
    description: Topic Publication. The request payload is the content of the message to be published.
    body:
      text/plain:
    responses:
      200: