#%RAML 0.8
title: pulsar-webapp
baseUri: http://example.com
documentation:
 - title: The PulSaR API
   content: |
     Optimization APIs (5.0)
/auth/menu: 
  get: 
    responses: 
      200: 
        body: 
          text/html: 
  post: 
    responses: 
      200: 
        body: 
          text/html: 
/gui:
  /admin:
    description: These are the administration requests
    /get-attribute/{attr_id}: 
      uriParameters:
        attr_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /save-attribute: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /exportBrokerPolicy: 
      get: 
        responses: 
          200: 
            body: 
              text/turtle;charset=utf-8: 
    /get-all-attributes: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /category-attribute-mappings/{cat_id}: 
      uriParameters:
        cat_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /create-attribute: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /delete-attribute/{attr_id}: 
      uriParameters:
        attr_id:
      get: 
        responses: 
          200: 
    /category-attribute-mappings/{id}: 
      uriParameters: 
        id:
      delete: 
        responses: 
          200: 
            body: 
              text/plain: 
    /importBrokerPolicy: 
      post: 
        body: 
          multipart/form-data: 
        responses: 
          200: 
  /consumer:
    /profile-create: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /profile-data/{profile_id}: 
      uriParameters:
        profile_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /profile-save: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /preference-attributes/category/{cat_id}/profile/{profile_id}: 
      uriParameters:
        cat_id:
        profile_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
      /selected: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
        post: 
          responses: 
            200: 
              body: 
                application/json: 
    /category-list: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /profile-list: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /preference-attributes/pairs/profile/{profile_id}: 
      uriParameters:
        profile_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /profile-delete/{profile_id}: 
      uriParameters:
        profile_id:
      get: 
        responses: 
          200: 
    /preference-attributes/profile/{profile_id}/calculate-weights: 
      uriParameters:
        profile_id:
      post: 
        responses: 
          200: 
            body: 
              application/json: 
    /preference-attributes/profile/{profile_id}/preferences/save: 
      uriParameters:
        profile_id:
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /preference-attributes/profile/{profile_id}/save:
      uriParameters:
        profile_id: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
  /feedback:
    /sd/{sd_id}: 
      uriParameters:
        sd_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      delete: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /used-services-list: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
  /notifications:
    /sd/{sd_id}/list: 
      uriParameters:
        sd_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /list-services: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
  /recommendations:
    /{recom_id}: 
      uriParameters:
        recom_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /list: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /{profile_id}/list: 
      uriParameters:
        profile_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /profile/{profileId}/make-permenent/{recomId}: 
      uriParameters:
        profileId:
        recomId:
      get: 
        responses: 
          200: 
            body: 
              text/html: 
    /{profile_id}/request: 
      uriParameters:
        profile_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /{item_id}/{response}: 
      uriParameters:
        item_id:
        response:
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
/opt:
  /attributes: 
    get: 
      responses: 
        200: 
          body: 
            application/json: 
    put: 
      body: 
        application/json: 
      responses: 
        200: 
    /{attr_id}: 
      uriParameters:
        attr_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      delete: 
        responses: 
          200: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
      /subattributes: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
    /all: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
  /aux/offerings:
    /category/{cat_id}:
      uriParameters:
        cat_id:
      /services/{serv_id}:
        uriParameters:
          serv_id:
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /specifications: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
    /sp/{sp}/list: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
  /feedback:
    /sc/{sc_id}:
      uriParameters:
        sc_id:
      /list-used-services/period/{period}: 
        uriParameters: 
          period: 
            type: integer
            required: true
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /sd/{sd_id}: 
        uriParameters:
          sd_id:
        get: 
          responses: 
            200: 
              body: 
                application/json: 
        delete: 
          body: 
            application/json: 
          responses: 
            200: 
              body: 
                application/json: 
        post: 
          body: 
            application/json: 
          responses: 
            200: 
              body: 
                application/json: 
    /sd/{sd_id}:
      uriParameters:
        sd_id:
      /notifications/period/{period}: 
        uriParameters: 
          period: 
            type: integer
            required: true
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /imprecise-attributes: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
  /notification/sd/{sdId}: 
    uriParameters:
      sdId:
    get: 
      responses: 
        200: 
          body: 
            application/json: 
    /period/{period_spec}/list: 
      uriParameters:
        period_spec:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
  /profile:
    /sc/{sc_id}:
      uriParameters:
        sc_id:
      /profile/{profile_id}:
        uriParameters:
          profile_id:
        get: 
          responses: 
            200: 
              body: 
                application/json: 
        delete: 
          responses: 
            200: 
        post: 
          body: 
            application/json: 
          responses: 
            200: 
      /detailed-list: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /list: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /profile/{profile_name}: 
        uriParameters:
          profile_name:
        put: 
          body: 
            application/json: 
          responses: 
            200:                 
    /category/{cat_id}/profiles: 
      uriParameters:
        cat_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /{profile_id}/criteria/weights: 
      uriParameters:
        profile_id:
      post: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
  /recommendation:
    description: Recommendations Management API
    /{recom_id}: 
      uriParameters:
        recom_id:
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      put: 
        body: 
          application/json: 
        responses: 
          200: 
      delete: 
        responses: 
          200: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
    /sc/{scId}/profile/{profileId}:
      uriParameters:
        scId:
        profileId:
      /period/{period_spec}/list: 
        uriParameters:
          period_spec:
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /request: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /clear-recommendations: 
        post: 
          responses: 
            200: 
              body: 
                application/json: 
    /item/{item_id}/{response}: 
      uriParameters:
        item_id:
        response:
      post: 
        body: 
          application/json: 
        responses: 
          200: 
  /service-category:
    /{cat_id}:
      uriParameters:
        cat_id:
      /attributes: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /attributes-all: 
        get: 
          responses: 
            200: 
              body: 
                application/json: 
    /attributes: 
      put: 
        body: 
          application/json: 
        responses: 
          200: 
      post: 
        body: 
          application/json: 
        responses: 
          200: 
      /{id}: 
        uriParameters:
          id:
        get: 
          responses: 
            200: 
              body: 
                application/json: 
      /{sca_id}:
        uriParameters:
          sca_id: 
        delete: 
          responses: 
            200: 
