#%RAML 0.8
title: Message Broker API
baseUri: http://example.com
documentation:
  - title: Message Broker API
    content: Hey
/subscriptions:    
  description: Topic Subscription Management
  /evaluation/SDReport/{clientId}:
    description: Temporary Subscription to Service Description Reports
    uriParameters:
      clientId:
        description: An identifier of the client that is subscribing.
    put:
      description: Topic Subscription Interfaces
      queryParameters:
        wsCallbackEndpoint:
          description: A valid WS endpoint which will receive a POST request when a new message arrives for the subscribed topic. 
      responses:
        204:
  /durable/SDReport/{clientId}:
      description: Durable Subscription to Service Description Reports
      uriParameters:
        clientId:
          description: An identifier of the client that is subscribing.
      put:
        description: Durable Topic Subscription
        queryParameters:
          wsCallbackEndpoint:
            description: A valid WS endpoint which will receive a POST request when a new message arrives for the subscribed topic. 
        responses:
          204:
  /durable/SDReport/{clientId}/unsubscribe:
      description: Unsubscribe from Durable Subscription to Service Description Reports
      uriParameters:
        clientId:
          description: An identifier of the client that is subscribing.
      put:
        description: Durable Topic unsubscription
        responses:
          204:
/topics/evaluation/SD/{clientId}:
  description: Publish Service Description
  uriParameters:
    clientId:
      description: An identifier of the client that is subscribing.
  post:
    description: Topic Publication. The request payload is the content of the message to be published.
    body:
      text/plain:
    responses:
      200: