package org.broker;

import java.io.File;
import java.io.IOException;

import org.broker.model.Service;
import org.jast.ast.ASTReader;
import org.jast.ast.ASTWriter;

/**
 * Program that reads an XML service specification into memory and writes it
 * back out to a second file.  Use this program to test whether a service
 * specification conforms to the expected syntax, or to see the serialised
 * XML format generated by the marshaller.
 * 
 * Requires ASTReader and ASTWriter from the JAST package.
 * 
 * @author Anthony J H Simons
 * @version Broker@Cloud 0.1
 */
public class CheckReadWrite {
	
	/**
	 * Name of the input file.  Change to suit.
	 */
	public static String inputFile = "StorageService.xml";
	
	/**
	 * Name of the output file.  Change to suit.
	 */
	public static String outputFile = "Output.xml";

	/**
	 * Reads an XML service specification from the input file, and, if no
	 * faults are found, writes the service specification to the output file.
	 * @param args empty.
	 * @throws IOException if an I/O error occurs.
	 */
	public static void main(String[] args) throws IOException {
		System.out.println("Starting program: CheckReadWrite.\n");
		
		ASTReader reader = new ASTReader(new File(inputFile));
		reader.usePackage("org.broker.model");
		Service service = (Service) reader.readDocument();
		reader.close();		
		
		System.out.println("Unmarshalled the model from input file: " + inputFile);
		
		ASTWriter writer = new ASTWriter(new File(outputFile));
		writer.usePackage("org.broker.model");
		writer.writeDocument(service);
		writer.close();

		System.out.println("Marshalled the model to output file: " + outputFile);
		
		System.out.println("\nProgram completed with success.");

	}

}
